### ISSUE TITLE
BlueTooth LE Issue?

### ISSUE THREAD

**Issue by madmacks59** [tgalarneau/bms#17]
I've got an old RPi 3b+ that I'm trying to set up. It's running raspbian bullseye (11). This was a fresh install. I'm running Python 3.9.2. I have the scripts installed and when I run jbdbms-4-socket-1temp.py I get the following
`pi@raspberrypi:~/Documents/bms-main $ python jbdbms-4-socket-1temp.py -b B3:FC:EC:38:C1:A4 -i 10 -m jbdProto

attempting to connect

2nd try connect

Traceback (most recent call last):
  File "/home/pi/Documents/bms-main/jbdbms-4-socket-1temp.py", line 160, in <module>
    bms = Peripheral(args.BLEaddress,addrType="public")
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral B3:FC:EC:38:C1:A4, addr type: public

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Documents/bms-main/jbdbms-4-socket-1temp.py", line 164, in <module>
    bms = Peripheral(args.BLEaddress,addrType="public")
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral B3:FC:EC:38:C1:A4, addr type: public

pi@raspberrypi:~/Documents/bms-main $`

When I use the Bluetooth widget to scan for devices I only see one device (not the BMS). A similar scan from my MacBook shows over a dozen devices including the BMS. I'm wondering if the Raspbian distribution doesn't have BLE support on by default. So I went to Terminal and ran bluetoothctl and then ran "scan on" an I see a nice list of devices including the BMS. But the control panel still doesn't show anything but one.

Is there some configuration option I need to set to have Python and the script see all the devices?

**Comment by madmacks59** [comment]
Never mind... the issue was that the XiaoxiangBMS software I was using to get the bluetooth address from lists it in reverse order. I noticed this when I ran the RPI bluetoothctl utility and ran a scan. Anyway, on to other issues as I try an get this running on my equipment...
